# Generated by Django 3.0.7 on 2020-06-13 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_relatorio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='celula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.Celula'),
            preserve_default=False,
        ),
    ]
